config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources  :users, only: [:index, :show, :update]
  post 'users/:id', to: 'users#shuffle'
  get '/about', to: 'pages#about'
  root to: 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :recipient, class_name: 'User', optional: true
  validates :name, presence: true, length: { maximum: 50 }

  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :photo, content_type: /\Aimage/
  validates_attachment_file_name :photo, matches: [/png\z/, /jpe?g\z/]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    current_user
  end

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:wishlist, :photo])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user,  only: [:show, :update, :edit]
  before_action :admin_user,    only: [:shuffle]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash.now[:info] = 'Wishlist updated.'
      render 'show'
    else
      flash[:danger] = 'Failed to update wishlist.'
      redirect_to 'show'
    end
  end

  def shuffle
    begin
      @user = current_user
      User.update_all recipient_id: nil
      User.update_all assigned: false
      users = User.all
      users.each do |user|
        recipients = users.where(["id != ? and NOT assigned", user])
        recipient = recipients.sample
        recipient.update_attribute(:assigned, true)
        user.recipient = recipient
        user.save unless recipient.nil?
      end
      flash[:success] = 'Santas assigned.'
    rescue NoMethodError => e
      flash[:danger] = 'Somebody got assigned to himself. Shuffle again.'
    end
    redirect_to user_path
  end

  private

    def user_params
      params.require(:user).permit(:name, :wishlist, :photo)
    end

    def is_logged_in?
      unless user_signed_in?
        flash[:info] = 'Please sign in first.'
        redirect_to new_user_session_path
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to root_url unless @user == current_user
    end

    def admin_user
      redirect_to root_url unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns full title
  def full_title(page_title = '')
    base = 'Secret Santa App'
    if page_title.empty?
      base
    else
      page_title + ' | ' + base
    end
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" unless devise_error_messages?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      :count => resource.errors.count,
                      :resource => resource.class.model_name.human.downcase)

    html = <<-HTML
    <div id="error_explanation" class="panel panel-danger">
      <div class="panel-heading">
        <h5>Please check if you meet the following requirements:</h5>
      </div>
      <div class="panel-body">
        <ul>#{messages}</ul>
      </div>
    </div>
    HTML

    html.html_safe
  end

  def devise_error_messages?
    !resource.errors.empty?
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div class="row">
  <footer>
    <small>
      Secret Santa (c) 2017
    </small>
  </footer>
</div>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <%= link_to  "Secret Santa", root_path, class: "navbar-brand" %>
        <button type="button" class="collapsed navbar-toggle" data-toggle="collapse" data-target="#collapsible-navbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      
      <div class="collapse navbar-collapse" id="collapsible-navbar">
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to current_user.name, current_user %></li>
            <li><%= link_to  "Participants", users_path %></li>
          <% else %>
            <li><%= link_to  "Home", root_path %></li>
          <% end %>
          <li><%= link_to  "About", about_path %></li>
          <% if user_signed_in? %>
            <li><%= link_to  "Sign Out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to  "Sign In", new_user_session_path %></li>
          <% end %>
        </ul>
      </div>
    </div> <!-- container-fluid -->
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  Can't find the time to meet with friends and draw your secret lucky friend?
  This website helps solve that problem! Sign up now with your friends
  so you can start exchanging gifts.
</p>

app/views/pages/home.html.erb
<div class="center jumbotron">
  <h1>Ho ho ho!</h1>
  <p>
    Welcome to the Secret Santa app!
  </p>
  <% unless user_signed_in? %>
    <%= link_to  "Sign up now!", new_user_registration_path, class: "btn btn-lg btn-success" %>
  <% end %>
</div>

app/views/users/_recipient_panel.html.erb
<div class="col-md-6">
  <div class="panel panel-info">
    <div class="panel-heading">
      <h4 class="panel-title">Recipient's wishlist</h4>
    </div>
    <div class="panel-body">
      <h5>You got <%= current_user.recipient.name %>!</h5>
      <dl>
        <dt>Wishlist</dt>
        <dd><%= simple_format(current_user.recipient.wishlist) %></dd>
      </dl>
      <%= image_tag current_user.recipient.photo.url(:medium),
                                                class: "img-responsive" if 
                                        current_user.recipient.photo.exists? %>

    </div>
  </div>
</div>

app/views/users/_wishlist_form.html.erb
<%= form_for @user, url: user_path, html: { multipart: true } do |f| %>
        
  <div class="form-group">
    <%= f.text_area :wishlist, placeholder: "Add your wishlist here.." %>
    <%= image_tag @user.photo.url(:thumb), class: "img-thumbnail" if @user.photo.exists? %>
  </div>
  
  <div class="form-group">
    <label>Attachment</label>
    <%= f.file_field :photo %>
  </div>
  
  <%= f.submit "Submit", class: "btn btn-primary" %>

<% end %>

app/views/users/index.html.erb
<h1>Participants</h1>
<div class="row">
  <ul class="list-group col-md-4 col-md-offset-4">
    <% @users.each do |user| %>
      <li class="list-group-item text-center"><%= user.name %></li>
    <% end %>
  </ul>
</div>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<div class="row">
  <div class="col-md-6">
    <div class="panel panel-primary">
      <div class="panel-heading"><h4 class="panel-title">Your wishlist</h4></div>
      <div class="panel-body">
        <%= render  'wishlist_form' %>
        <% if current_user.admin? %>
        <div>
          <label>Shuffle players?</label>
          <%= button_to  "Shuffle", { action: "shuffle" }, { class: "btn btn-danger" } %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
  <% if !(current_user.recipient_id.nil?) %>
    <%= render 'recipient_panel' %>
  <% end %>
</div>